from pathlib import Path
p=Path('app/page.tsx');s=p.read_text(encoding="utf-8");s=s.replace("[message,setMessage]=useState('');", "[message,setMessage]=useState(''),[mobile,setMobile]=useState(''),[mobileConsent,setMobileConsent]=useState(false),[pendingProduct,setPendingProduct]=useState<Product|null>(null),[couponCode,setCouponCode]=useState(''),[appliedCoupon,setAppliedCoupon]=useState({code:'',discount:0}),[note,setNote]=useState(''),[activeChapter,setActiveChapter]=useState(0);")
s=s.replace("useEffect(()=>{load();},[]);", "useEffect(()=>{load();const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');const n=e.target.getAttribute('data-chapter');if(n)setActiveChapter(Number(n));}}),{threshold:0.25});document.querySelectorAll('.scroll-chapter,.reveal').forEach(el=>observer.observe(el));return ()=>observer.disconnect();},[]);")
s=s.replace("setCart(d.cart);}", "setCart(d.cart);setAppliedCoupon({code:'',discount:0});}")
s=s.replace("function show(p:Product){setDetail(p);", "function show(p:Product){if(!user){setPendingProduct(p);setPanel('mobile');return;}setDetail(p);")
s=s.replace("toast.success('Added to your bag');setDetail(null);", "toast.success('Added to your bag');setDetail(null);setPanel('bag');")
s=s.replace("account:'Your TREND ZEE',", "account:'Your TREND ZEE',mobile:'Your next chapter starts here',")
s=s.replace("{(panel==='account'||panel==='checkout'||panel==='feedback')&&!user&&", "{panel==='mobile'&&<form onSubmit={e=>{e.preventDefault();run(async()=>{await api('mobile',{mobile,consent:mobileConsent});await load();setPanel('');if(pendingProduct){setDetail(pendingProduct);setSize(pendingProduct.sizes[0]);setColor(pendingProduct.colors[0]);setPhoto(0);setPendingProduct(null);}else setPanel('account');});}}><p>Enter your mobile number to start shopping. We'll keep your bag together as you explore.</p><label>Mobile number<input type=\"tel\" inputMode=\"tel\" autoComplete=\"tel\" required maxLength={13} placeholder=\"Your mobile number\" value={mobile} onChange={e=>setMobile(e.target.value.replace(/[^0-9+]/g,''))}/></label><label className=\"check-line\"><Checkbox checked={mobileConsent} onCheckedChange={v=>setMobileConsent(v===true)}/><span>I agree to save my number and shopping activity so TREND ZEE can help with an unfinished purchase.</span></label><p className=\"small muted\">Guest shopping preview. Your number is not OTP verified, and entering it does not give access to another session's orders.</p><button className=\"button full\" disabled={busy||!mobileConsent}>{busy?'Continuing…':'Continue shopping'}</button></form>}\n{(panel==='account'||panel==='checkout'||panel==='feedback')&&!user&&")
s=s.replace('<a className="button" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>', '<button className="button" onClick={()=>setPanel(\'mobile\')}>Continue with mobile number</button>')
s=s.replace('Customer email/mobile authentication will be connected with Supabase.', 'Verified mobile sign-in will be available when the store launches.')
s=s.replace('<p className="small muted">Signed in as {user.email}</p><a className="text-button" href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a>', '<p className="small muted">{user.guest?\'Guest shopping session · Mobile not verified\':\'Signed in as \'+user.email}</p>{!user.guest&&<a className="text-button" href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a>}')
s=s.replace("api('checkoutStart',{profile,consent})", "api('checkoutStart',{profile,consent,coupon:appliedCoupon.code})")
s=s.replace("api('order',{profile,consent,method,key:", "api('order',{profile,consent,method,coupon:appliedCoupon.code,note,key:")
s=s.replace("{profileForm()}<label className=\"check-line\">", "{profileForm()}<label>Delivery instructions (optional)<textarea rows={2} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder=\"Landmark or delivery instructions\"/></label><div className=\"coupon-row\"><label>Have a coupon?<input value={couponCode} onChange={e=>{setCouponCode(e.target.value.toUpperCase());setAppliedCoupon({code:'',discount:0});}} placeholder=\"Enter coupon code\"/></label><button type=\"button\" className=\"button outline\" disabled={busy||!couponCode} onClick={()=>run(async()=>{const d=await api('coupon',{code:couponCode});setAppliedCoupon(d);toast.success('Coupon applied');})}>Apply</button></div>{appliedCoupon.code&&<p className=\"coupon-success\">{appliedCoupon.code} applied · You save {money(appliedCoupon.discount)}</p>}<div className=\"billing-summary\"><h3>Your order summary</h3>{cart.items.map((i,index)=><div className=\"split\" key={index}><span>{i.name} × {i.quantity}</span><b>{money((i.price||0)*i.quantity)}</b></div>)}<div className=\"split\"><span>Subtotal</span><span>{money(total)}</span></div>{appliedCoupon.discount>0&&<div className=\"split\"><span>Coupon savings</span><span>−{money(appliedCoupon.discount)}</span></div>}<p className=\"small muted\">Delivery and taxes: to be confirmed before accepting paid orders.</p><div className=\"total\"><b>Request total</b><b>{money(total-appliedCoupon.discount)}</b></div></div><label className=\"check-line\">")
s=s.replace('<b>{money(total)}</b></div><button className="button full" disabled={busy}', '<b>{money(total-appliedCoupon.discount)}</b></div><button className="button full" disabled={busy}')
start=s.index('<section className="chapters">');end=s.index('<section className="story"',start)
s=s[:start]+'''<section className="scrollytelling" aria-label="A day in TREND ZEE"><div className="story-intro reveal"><div className="eyebrow">ONE DAY. A THOUSAND POSSIBILITIES.</div><h2>You don't live<br/>in just <em>one moment.</em></h2><p>So why dress like it?<br/>Scroll through a day that feels like you.</p><span className="scroll-line"/></div><div className="chapter-progress" aria-hidden="true">{['08:00 / START EASY','12:30 / GO SOMEWHERE','18:00 / FIND YOUR PACE'].map((label,i)=><span key={label} className={activeChapter===i+1?'active':''}>{label}</span>)}</div>{[{n:1,time:'08:00',title:'Before the world wakes.',italic:'Make it yours.',text:'The light through the window. A coffee made just right. That favourite shirt you reach for without thinking. Some of the best parts of your day happen before it begins.',category:'Clothing',cta:'Find your everyday layer',image:'/images/hero.jpg',alt:'Relaxed menswear for the start of the day',detail:'CHAPTER ONE / THE EVERYDAY LAYER'},{n:2,time:'12:30',title:'Plans change.',italic:'Carry possibility.',text:'A laptop. A notebook full of ideas. The essentials that make an ordinary day your own. From the office to a spontaneous detour, take a little room for what comes next.',category:'Bags',cta:'Find your everyday carry',image:'/images/bag.jpg',alt:'Brown backpack for everyday essentials',detail:'CHAPTER TWO / OUT IN THE WORLD'},{n:3,time:'18:00',title:'Take the long way.',italic:'Find your pace.',text:'One more street. One more conversation. The city looks different when you slow down. Step out of the schedule and into the moments you will remember.',category:'Shoes & Sandals',cta:'Find your next step',image:'/images/sneaker.jpg',alt:'Sneakers for a walk through the city',detail:'CHAPTER THREE / THE LONG WAY HOME'}].map(c=><article className={'scroll-chapter chapter-'+c.n} data-chapter={c.n} key={c.n}><div className="chapter-visual"><img src={c.image} alt={c.alt}/><span className="chapter-time">{c.time}</span><span className="chapter-image-label">TREND ZEE / EVERYDAY STORIES</span></div><div className="chapter-copy"><span className="chapter-number">0{c.n}</span><div className="eyebrow">{c.detail}</div><h2>{c.title}<br/><em>{c.italic}</em></h2><p>{c.text}</p><button className="button" onClick={()=>browse(c.category)}>{c.cta}</button></div></article>)}<div className="night-chapter reveal"><div className="eyebrow">21:00 / COME BACK TO YOURSELF</div><h2>Big day.<br/><em>Small comforts.</em></h2><p>Kick back. Leave the day at the door.<br/>Your off-duty chapter deserves a good fit, too.</p><button className="button light-button" onClick={()=>browse('Slippers')}>Slip into something easy</button></div></section>'''+s[end:]
p.write_text(s,encoding="utf-8")

