'use client';

import {useEffect,useState} from 'react';
import {ArrowLeft,Heart,ShoppingBag,Share2,TrendingDown,TrendingUp} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {money,Product} from '@/lib/catalog';
import {api} from '@/lib/client';

export default function WishlistPage(){
 const [products,setProducts]=useState<Product[]>([]);const [items,setItems]=useState<string[]>([]);const [cart,setCart]=useState<any>({items:[]});const [priceChanges,setPriceChanges]=useState<Record<string,{old:number;now:number}>>({});const [loading,setLoading]=useState(true);
 const load=async()=>{const r=await fetch('/api/store');const d:any=await r.json();if(!r.ok)throw new Error(d.error);const next=d.products||[];setProducts(next);setItems(d.cart?.saved||[]);setCart(d.cart||{items:[]});try{const key='tz_wishlist_prices';const previous=JSON.parse(localStorage.getItem(key)||'{}');const changes:Record<string,{old:number;now:number}>={};for(const p of next){if(d.cart?.saved?.includes(p.id)&&previous[p.id]&&Number(previous[p.id])!==Number(p.price))changes[p.id]={old:Number(previous[p.id]),now:Number(p.price)};}setPriceChanges(changes);const snapshot={...previous,...Object.fromEntries(next.filter((p:any)=>d.cart?.saved?.includes(p.id)).map((p:any)=>[p.id,p.price]))};localStorage.setItem(key,JSON.stringify(snapshot));}catch{}};
 useEffect(()=>{load().catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[]);
 async function update(saved:string[],nextCart=cart.items){try{const d=await api('cart',{items:nextCart,saved});setItems(d.cart.saved);setCart(d.cart);toast.success('Wishlist updated')}catch(e){toast.error((e as Error).message)}}
 async function move(p:Product){if(!p.stock)return;const existing=cart.items.find((i:any)=>i.productId===p.id&&i.size===p.sizes[0]&&i.color===p.colors[0]);const next=cart.items.map((i:any)=>({...i}));if(existing)next[next.indexOf(existing)]={...existing,quantity:Math.min(p.stock,Math.min(10,existing.quantity+1))};else next.push({productId:p.id,quantity:1,size:p.sizes[0],color:p.colors[0]});await update(items.filter(id=>id!==p.id),next)}
 if(loading)return <div className="store-loading"><span className="logo">TREND ZEE</span><p>Loading wishlist…</p></div>;
 const savedProducts=items.map(id=>products.find(p=>p.id===id)).filter(Boolean) as Product[];
 return <><Toaster richColors/><header className="store-header"><a className="logo" href="/">TREND ZEE<sup>®</sup></a><div className="header-actions"><a href="/shop">Shop</a><a href="/account">Account</a></div></header><main className="wishlist-page-shell"><a className="text-button" href="/shop"><ArrowLeft size={16}/> Back to shop</a><section className="wishlist-hero"><div><span className="eyebrow">YOUR SAVED EDIT</span><h1>Keep the pieces you’re not ready to forget.</h1><p>{savedProducts.length} saved item{savedProducts.length===1?'':'s'} · stock and price updates stay live.</p></div><button className="button outline" onClick={async()=>{const text=savedProducts.map(p=>p.name+' — '+money(p.price)).join('\n');try{await navigator.share?.({title:'My Trend-Zee wishlist',text,url:location.origin+'/wishlist'});if(!navigator.share){await navigator.clipboard.writeText('My Trend-Zee wishlist:\n'+text+'\n'+location.origin+'/wishlist');toast.success('Wishlist link copied')}}catch{}}}><Share2 size={16}/> Share wishlist</button></section>{savedProducts.length?<div className="shop-grid">{savedProducts.map(p=><article className="shop-card" key={p.id}><a href={'/product/'+p.id} className="shop-card-img"><img src={p.images[0]} alt={p.name} loading="lazy"/><span>{p.stock>0?'In stock':'Out of stock'}</span></a><div className="shop-card-body"><div className="split"><a href={'/product/'+p.id}><h2>{p.name}</h2></a><b>{money(p.price)}</b></div><p>{p.brand} · {p.type}</p>{priceChanges[p.id]&&<div className={'wishlist-price-change '+(priceChanges[p.id].now<priceChanges[p.id].old?'down':'up')}>{priceChanges[p.id].now<priceChanges[p.id].old?<TrendingDown size={13}/>:<TrendingUp size={13}/>} Price changed from {money(priceChanges[p.id].old)} to {money(priceChanges[p.id].now)}</div>}<div className="wishlist-actions"><button className="button" disabled={!p.stock} onClick={()=>move(p)}><ShoppingBag size={15}/> Move to bag</button><button className="text-button danger-text" onClick={()=>update(items.filter(id=>id!==p.id))}><Heart size={15}/> Remove</button></div></div></article>)}</div>:<div className="empty"><Heart size={36}/><h2>Your wishlist is waiting.</h2><p>Save products from the catalogue and return here when you're ready.</p><a className="button" href="/shop">Find your next favourite</a></div>}</main></>;
}
