'use client';

import {useEffect,useState} from 'react';
import {ArrowLeft,Bell,Heart,LogOut,MapPin,Package,RotateCcw,Save,ShieldCheck,UserRound} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {money} from '@/lib/catalog';
import {api} from '@/lib/client';

export default function AccountPage(){
 const [user,setUser]=useState<any>(null);const [profile,setProfile]=useState<any>({name:'',email:'',mobile:'',address:'',city:'',pincode:'',location:''});const [orders,setOrders]=useState<any[]>([]);const [returns,setReturns]=useState<any[]>([]);const [support,setSupport]=useState<any[]>([]);const [saved,setSaved]=useState<string[]>([]);const [tab,setTab]=useState('orders');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 async function load(){const r=await fetch('/api/store');const d:any=await r.json();if(!r.ok)throw new Error(d.error);setUser(d.user);setProfile(d.profile||profile);setOrders(d.orders||[]);setReturns(d.returns||[]);setSupport(d.support||[]);setSaved(d.cart?.saved||[])}
 useEffect(()=>{load().catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[]);
 async function saveProfile(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await api('profile',{profile});setProfile(r.profile);toast.success('Account details saved')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 if(loading)return <div className="store-loading"><span className="logo">TREND ZEE</span><p>Loading your account…</p></div>;
 if(!user)return <main className="account-page-shell"><Toaster richColors/><a className="text-button" href="/"><ArrowLeft size={16}/> Back to shop</a><div className="account-gate"><UserRound size={36}/><h1>Your shopping space.</h1><p>Sign in from Trend-Zee to view orders, saved details and support history.</p><a className="button" href="/">Continue to Trend-Zee</a></div></main>;
 return <><Toaster richColors/><header className="store-header"><a className="logo" href="/">TREND ZEE<sup>®</sup></a><div className="header-actions"><a href="/shop">Shop</a><a href="/wishlist"><Heart size={19}/></a><a href="/#collection">Bag</a></div></header><main className="account-page-shell"><div className="product-page-top"><a className="text-button" href="/"><ArrowLeft size={16}/> Back to shop</a><a className="text-button" href="/signout-with-chatgpt?return_to=/" target="_top"><LogOut size={15}/> Sign out</a></div><section className="account-head"><span className="eyebrow">MY TREND-ZEE</span><h1>Everything you’re shopping around.</h1><p>{user.displayName||user.email}</p></section><nav className="account-route-tabs">{['orders','profile','support','returns','wishlist'].map(x=><button className={tab===x?'active':''} key={x} onClick={()=>{if(x==='wishlist')location.href='/wishlist';else setTab(x)}}>{x}</button>)}</nav>
 {tab==='orders'&&<section className="account-panel"><div className="card-head"><div><span className="eyebrow">ORDER HISTORY</span><h2>Track every order.</h2></div></div>{orders.length?orders.map(o=><article className="account-order" key={o.id}><div className="split"><div><b>{o.id}</b><small>{new Date(o.created).toLocaleString('en-IN')}</small></div><span className="status-pill">{o.status}</span></div><div className="order-mini-items">{(o.items||[]).map((i:any)=><span key={i.productId+i.size+i.color}>{i.name} × {i.quantity}</span>)}</div><div className="split"><span>{money(o.total)}</span><span>{o.paymentStatus} · {o.method}</span></div>{o.tracking&&<p className="notice"><Package size={15}/> {o.courier||'Courier'} · {o.tracking}</p>}<div className="order-timeline"><span className="done">Requested</span><span className={o.paymentStatus==='Paid'?'done':''}>Paid</span><span className={['Processing','Dispatched','Delivered'].includes(o.status)?'done':''}>Processing</span><span className={['Dispatched','Delivered'].includes(o.status)?'done':''}>Dispatched</span><span className={o.status==='Delivered'?'done':''}>Delivered</span></div></article>):<div className="empty"><Package size={32}/><h2>No orders yet.</h2><a className="button" href="/shop">Start shopping</a></div>}</section>}
 {tab==='profile'&&<section className="account-panel"><div className="account-feature-grid"><div className="account-feature"><ShieldCheck size={18}/><b>Identity</b><small>{user.email}</small></div><div className="account-feature"><Heart size={18}/><b>Wishlist</b><small>{saved.length} saved item{saved.length===1?'':'s'}</small></div><div className="account-feature"><Bell size={18}/><b>Notifications</b><small>Preference controls can be connected to email/SMS providers.</small></div></div><form className="form-grid account-form" onSubmit={saveProfile}><label>Full name<input required value={profile.name||''} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Email<input type="email" required value={profile.email||''} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label>Mobile<input required value={profile.mobile||''} onChange={e=>setProfile({...profile,mobile:e.target.value})}/></label><label className="wide">Address<textarea required rows={3} value={profile.address||''} onChange={e=>setProfile({...profile,address:e.target.value})}/></label><label>City<input required value={profile.city||''} onChange={e=>setProfile({...profile,city:e.target.value})}/></label><label>PIN code<input required maxLength={6} value={profile.pincode||''} onChange={e=>setProfile({...profile,pincode:e.target.value.replace(/\D/g,'' )})}/></label><div className="wide"><button className="button" disabled={busy}><Save size={15}/> Save profile & delivery address</button></div></form><p className="notice"><MapPin size={15}/> Delivery serviceability, tax calculation and transactional notifications are provider integrations; the account is ready to hold the required data.</p></section>}
 {tab==='support'&&<section className="account-panel"><div className="card-head"><div><span className="eyebrow">SUPPORT</span><h2>Help that stays with the account.</h2></div></div>{support.length?support.map(t=><article className="support-ticket" key={t.id}><div className="split"><b>{t.id}</b><span className="status-pill">{t.status}</span></div><h3>{t.subject}</h3><p>{t.message}</p><small>{t.category} · {new Date(t.created).toLocaleString('en-IN')}</small></article>):<div className="empty"><p>No tickets yet.</p></div>}<a className="button" href="/#support">Contact support</a></section>}
 {tab==='returns'&&<section className="account-panel"><div className="card-head"><div><span className="eyebrow">RETURNS & REFUNDS</span><h2>Keep the after-sale experience clear.</h2></div></div>{returns.length?returns.map(r=><article className="support-ticket" key={r.id}><div className="split"><b>{r.id}</b><span className="status-pill">{r.status}</span></div><p>Order {r.orderId}</p><p>{r.reason}</p><small>{money(r.refundAmount||r.total||0)} expected value · {new Date(r.created).toLocaleString('en-IN')}</small></article>):<div className="empty"><RotateCcw size={32}/><p>No return requests yet.</p></div>}<p className="notice">Refunds are only marked as processed after a verified payment/refund provider is connected.</p></section>}
 </main></>;
}
