'use client';

import {useState} from 'react';
import {ArrowDown,ArrowUp,Eye,EyeOff,ImagePlus,Pencil,Plus,RotateCcw,Trash2,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogTitle} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
import {ANIMATIONS,ANIMATION_LABELS,SECTION_LABELS,SECTION_TYPES,isLive,newSection,type Section,type SectionItem,type SectionType} from '@/lib/home';
import type {Product} from '@/lib/catalog';

type Props={sections:Section[];isDefault:boolean;products:Product[];api:(action:string,data?:Record<string,unknown>)=>Promise<any>;reload:()=>Promise<void>;run:(fn:()=>Promise<void>)=>Promise<void>;busy:boolean};
const toLocal=(iso:string)=>{if(!iso)return '';const d=new Date(iso),p=(n:number)=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())+'T'+p(d.getHours())+':'+p(d.getMinutes())};
const fromLocal=(s:string)=>s?new Date(s).toISOString():'';
const status=(s:Section)=>{const now=new Date().toISOString();if(!s.visible)return ['Hidden','off'];if(s.startsAt&&s.startsAt>now)return ['Scheduled','wait'];if(s.endsAt&&s.endsAt<now)return ['Ended','off'];return isLive(s)?['Live','on']:['Hidden','off']};
const hasItems=(t:SectionType)=>['trustBar','categoryShowcase','testimonials','brandLogos'].includes(t);
const hasImage=(t:SectionType)=>['hero','collectionBanner','fullImage','video','promoBanner','cta','editorial','brandLogos'].includes(t);
const hasButtons=(t:SectionType)=>!['trustBar','categoryShowcase','testimonials'].includes(t);
const hasSecondary=(t:SectionType)=>['hero','collectionBanner','promoBanner','cta'].includes(t);

export default function AdminHomeBuilder({sections,isDefault,products,api,reload,run,busy}:Props){
 const [draft,setDraft]=useState<Section|null>(null);const [removing,setRemoving]=useState<Section|null>(null);const [resetting,setResetting]=useState(false);const [newType,setNewType]=useState<SectionType>('productRow');const [uploading,setUploading]=useState('');const [draggedId,setDraggedId]=useState('');const [dropTargetId,setDropTargetId]=useState('');
 const ordered=[...sections].sort((a,b)=>a.order-b.order);const categories=Array.from(new Set(products.map(p=>p.category))).sort();
 const move=(i:number,d:-1|1)=>run(async()=>{const ids=ordered.map(s=>s.id),j=i+d;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];await api('adminSectionOrder',{ids});await reload()});
 const saveSection=()=>draft&&run(async()=>{await api('adminSection',{section:draft});await reload();setDraft(null);toast.success('Homepage section saved.')});
 const dragDrop=async(targetId:string)=>{
   if(!draggedId||draggedId===targetId)return;
   const ids=ordered.map(s=>s.id);const from=ids.indexOf(draggedId),to=ids.indexOf(targetId);if(from<0||to<0)return;
   ids.splice(from,1);ids.splice(to,0,draggedId);await api('adminSectionOrder',{ids});await reload();
 };
 const toggle=(s:Section)=>run(async()=>{await api('adminSection',{section:{...s,visible:!s.visible}});await reload();toast.success(s.visible?'Section hidden.':'Section visible.')});
 const upload=async(file:File,apply:(url:string)=>void,key:string)=>{setUploading(key);try{const body=new FormData();body.append('file',file);const r=await fetch('/api/upload',{method:'POST',body});const j:any=await r.json();if(!r.ok)throw new Error(j.error||'Upload failed');apply(j.url)}catch(e){toast.error((e as Error).message)}finally{setUploading('')}};
 const set=<K extends keyof Section>(k:K,v:Section[K])=>setDraft(d=>d?{...d,[k]:v}:d);
 const setItem=(n:number,p:Partial<SectionItem>)=>setDraft(d=>d?{...d,items:d.items.map((it,i)=>i===n?{...it,...p}:it)}:d);
 const imageField=(label:string,key:'image'|'mobileImage')=><div className="hb-field"><label>{label}</label><div className="hb-image-row">{draft?.[key]?<img src={draft[key]} alt=""/>:<span className="hb-image-empty">No image</span>}<label className="hb-upload"><ImagePlus size={15}/> {uploading===key?'Uploading…':'Upload'}<input type="file" hidden accept="image/jpeg,image/png,image/webp" disabled={!!uploading} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)upload(f,u=>set(key,u),key)}}/></label>{draft?.[key]&&<button type="button" className="hb-icon" onClick={()=>set(key,'')}><X size={15}/></button>}</div><input value={draft?.[key]||''} onChange={e=>set(key,e.target.value)} placeholder="…or paste an https:// image URL"/></div>;
 return <div className="hb"><div className="hb-top"><div><h2>Homepage builder</h2><p>Reorder, hide, schedule and animate the shopping story. {isDefault&&<b> Starter layout until your first change is saved.</b>}</p></div><div className="hb-add"><select value={newType} onChange={e=>setNewType(e.target.value as SectionType)}>{SECTION_TYPES.map(t=><option key={t}>{SECTION_LABELS[t].label}</option>)}</select><button className="hb-btn" disabled={busy} onClick={()=>setDraft(newSection(newType,ordered.length))}><Plus size={16}/> Add section</button>{!isDefault&&<button className="hb-btn hb-ghost" disabled={busy} onClick={()=>setResetting(true)}><RotateCcw size={16}/> Reset</button>}</div></div>
 <ol className="hb-list">{ordered.map((s,i)=>{const st=status(s);return <li key={s.id} draggable={!busy} className={`${st[1]==='off'?'is-off ':''}${draggedId===s.id?'is-dragging ':''}${dropTargetId===s.id?'is-drop-target':''}`} onDragStart={()=>setDraggedId(s.id)} onDragOver={e=>{e.preventDefault();setDropTargetId(s.id)}} onDrop={e=>{e.preventDefault();void run(async()=>{await dragDrop(s.id)});setDraggedId('');setDropTargetId('')}} onDragEnd={()=>{setDraggedId('');setDropTargetId('')}}><div className="hb-move"><button aria-label="Move up" disabled={busy||i===0} onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button aria-label="Move down" disabled={busy||i===ordered.length-1} onClick={()=>move(i,1)}><ArrowDown size={15}/></button></div><div className="hb-info"><span className="hb-drag-handle" aria-hidden="true">⋮⋮</span><b>{s.title||SECTION_LABELS[s.type].label}</b><small>{SECTION_LABELS[s.type].label} · {ANIMATION_LABELS[s.animation]}</small></div><span className={'hb-status hb-'+st[1]}>{st[0]}</span><div className="hb-actions"><button onClick={()=>toggle(s)} aria-label="Toggle visibility">{s.visible?<Eye size={15}/>:<EyeOff size={15}/>}</button><button onClick={()=>setDraft(JSON.parse(JSON.stringify(s)))} aria-label="Edit"><Pencil size={15}/></button><button onClick={()=>setRemoving(s)} aria-label="Remove"><Trash2 size={15}/></button></div></li>})}{!ordered.length&&<li className="hb-empty">No sections yet.</li>}</ol>
 <Dialog open={!!draft} onOpenChange={v=>!v&&setDraft(null)}><DialogContent className="panel-dialog wide-dialog"><DialogTitle>{draft?SECTION_LABELS[draft.type].label:'Homepage section'}</DialogTitle><DialogDescription>Content, presentation, product sources and scheduling.</DialogDescription>{draft&&<form className="hb-form" onSubmit={e=>{e.preventDefault();saveSection()}}>
  <div className="hb-grid"><div className="hb-field"><label>Eyebrow</label><input maxLength={80} value={draft.eyebrow} onChange={e=>set('eyebrow',e.target.value)}/></div><div className="hb-field"><label>Title</label><input maxLength={160} value={draft.title} onChange={e=>set('title',e.target.value)}/></div></div>
  <div className="hb-field"><label>Supporting text</label><textarea rows={3} maxLength={700} value={draft.subtitle} onChange={e=>set('subtitle',e.target.value)}/></div>
  {hasImage(draft.type)&&<div className="hb-grid">{imageField('Desktop image','image')}{imageField('Mobile image','mobileImage')}</div>}
  {hasButtons(draft.type)&&<div className="hb-grid"><div className="hb-field"><label>Main CTA</label><input value={draft.ctaLabel} onChange={e=>set('ctaLabel',e.target.value)}/></div><div className="hb-field"><label>Main link</label><input value={draft.ctaHref} onChange={e=>set('ctaHref',e.target.value)}/></div>{hasSecondary(draft.type)&&<><div className="hb-field"><label>Secondary CTA</label><input value={draft.secondaryLabel} onChange={e=>set('secondaryLabel',e.target.value)}/></div><div className="hb-field"><label>Secondary link</label><input value={draft.secondaryHref} onChange={e=>set('secondaryHref',e.target.value)}/></div></>}</div>}
  {(draft.type==='productRow'||draft.type==='productGrid'||draft.type==='recommendations')&&<fieldset className="hb-field"><legend>Product source</legend><div className="hb-seg">{(['manual','newest','bestSellers','recommended','category'] as const).map(v=><label key={v} className={draft.source===v?'on':''}><input type="radio" checked={draft.source===v} onChange={()=>set('source',v)}/>{v==='manual'?'Hand-picked':v==='newest'?'Newest':v==='bestSellers'?'Best sellers':v==='recommended'?'Recommended':'Category'}</label>)}</div>{draft.source==='category'&&<select value={draft.category} onChange={e=>set('category',e.target.value)}><option value="">Choose category</option>{categories.map(c=><option key={c}>{c}</option>)}</select>}{draft.source==='manual'&&<div className="hb-picks">{products.map(p=><label key={p.id}><input type="checkbox" checked={draft.productIds.includes(p.id)} onChange={e=>set('productIds',e.target.checked?[...draft.productIds,p.id].slice(0,24):draft.productIds.filter(x=>x!==p.id))}/><img src={p.images[0]} alt=""/><span>{p.name}</span></label>)}</div>}</fieldset>}
  {hasItems(draft.type)&&<fieldset className="hb-field"><legend>{draft.type==='testimonials'?'Genuine customer quotes':'Content items'}</legend>{draft.items.map((it,n)=><div className="hb-item" key={n}><input placeholder={draft.type==='testimonials'?'Customer name':'Title'} value={it.title} onChange={e=>setItem(n,{title:e.target.value})}/><input placeholder="Text" value={it.text} onChange={e=>setItem(n,{text:e.target.value})}/><input placeholder="Image URL (optional)" value={it.image} onChange={e=>setItem(n,{image:e.target.value})}/><input placeholder="Link" value={it.href} onChange={e=>setItem(n,{href:e.target.value})}/><button type="button" className="hb-icon" onClick={()=>set('items',draft.items.filter((_,i)=>i!==n))}><X size={15}/></button></div>)}{draft.items.length<8&&<button type="button" className="hb-btn hb-ghost" onClick={()=>set('items',[...draft.items,{title:'',text:'',image:'',href:''}])}><Plus size={15}/> Add item</button>}</fieldset>}
  {draft.type==='video'&&<div className="hb-field"><label>Video URL</label><input value={draft.video||''} onChange={e=>set('video',e.target.value)} placeholder="https://…/campaign.mp4"/></div>}
  <div className="hb-grid hb-grid-3"><div className="hb-field"><label>Align</label><select value={draft.align} onChange={e=>set('align',e.target.value as Section['align'])}><option value="left">Left</option><option value="center">Centre</option><option value="right">Right</option></select></div><div className="hb-field"><label>Theme</label><select value={draft.theme} onChange={e=>set('theme',e.target.value as Section['theme'])}><option value="light">Light</option><option value="dark">Dark</option><option value="accent">Accent</option></select></div><div className="hb-field"><label>Animation</label><select value={draft.animation} onChange={e=>set('animation',e.target.value as Section['animation'])}>{ANIMATIONS.map(a=><option key={a} value={a}>{ANIMATION_LABELS[a]}</option>)}</select></div></div>
  <div className="hb-grid"><div className="hb-field"><label>Show from</label><input type="datetime-local" value={toLocal(draft.startsAt)} onChange={e=>set('startsAt',fromLocal(e.target.value))}/></div><div className="hb-field"><label>Show until</label><input type="datetime-local" value={toLocal(draft.endsAt)} onChange={e=>set('endsAt',fromLocal(e.target.value))}/></div></div>
  <label className="hb-check"><input type="checkbox" checked={draft.visible} onChange={e=>set('visible',e.target.checked)}/> Visible on storefront</label>
  <div className="hb-foot"><button type="button" className="hb-btn hb-ghost" onClick={()=>setDraft(null)}>Cancel</button><button className="hb-btn" disabled={busy||!!uploading}>Save section</button></div>
 </form>}</DialogContent></Dialog>
 <AlertDialog open={!!removing} onOpenChange={v=>!v&&setRemoving(null)}><AlertDialogContent><AlertDialogTitle>Remove this section?</AlertDialogTitle><AlertDialogDescription>This removes “{removing?.title||''}” from the homepage.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep it</AlertDialogCancel><AlertDialogAction onClick={()=>removing&&run(async()=>{await api('adminSectionDelete',{id:removing.id});await reload();setRemoving(null);toast.success('Section removed.')})}>Remove</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={resetting} onOpenChange={setResetting}><AlertDialogContent><AlertDialogTitle>Reset homepage?</AlertDialogTitle><AlertDialogDescription>Restore the starter shopping journey.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>run(async()=>{await api('adminSectionsReset');await reload();setResetting(false);toast.success('Homepage reset.')})}>Reset</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
