export type Product={id:string;name:string;category:string;type:string;brand:string;price:number;stock:number;colors:string[];sizes:string[];images:string[];description:string;specifications:string;tag:string;};
export const categories=['All','Clothing','Bags','Shoes & Sandals','Slippers','Sunglasses'];
export const seedProducts:Product[]=[
{id:'tz-001',name:'The everyday crew',category:'Clothing',type:'Round neck T-shirts',brand:'TREND ZEE',price:799,stock:30,colors:['White','Black'],sizes:['S','M','L','XL'],images:['/images/tee.jpg'],description:'A fresh start, every day. An easy crewneck for slow mornings, busy afternoons and everything in between.',specifications:'Sample product • Cotton jersey • Regular fit • Machine wash cold',tag:'THE DAILY ESSENTIAL'},
{id:'tz-002',name:'The city sneaker',category:'Shoes & Sandals',type:'Casual',brand:'TREND ZEE',price:2499,stock:18,colors:['White / Sand'],sizes:['6','7','8','9','10','11'],images:['/images/sneaker.jpg'],description:'Take the long way home. A versatile sneaker to carry your story from one street to the next.',specifications:'Sample product • Lace-up • Rubber outsole • Wipe clean',tag:'OFF THE CLOCK'},
{id:'tz-003',name:'The daytripper backpack',category:'Bags',type:'College bags',brand:'TREND ZEE',price:1899,stock:15,colors:['Brown'],sizes:['One size'],images:['/images/bag.jpg'],description:'Room for your plans. A compact carryall for your notebook, everyday essentials and a little spontaneity.',specifications:'Sample product • Adjustable straps • Zipped main compartment • Spot clean',tag:'GO SOMEWHERE'},
{id:'tz-004',name:'The after-hours shirt',category:'Clothing',type:'Mixed cotton',brand:'TREND ZEE',price:1499,stock:20,colors:['Blue'],sizes:['S','M','L','XL'],images:['/images/shirt.jpg'],description:'When the day changes pace, change the mood. A statement shirt for evenings worth remembering.',specifications:'Sample product • Collared shirt • Regular fit • Fabric to be confirmed',tag:'A LITTLE DIFFERENT'},
{id:'tz-005',name:'The weekend sandal',category:'Shoes & Sandals',type:'Home',brand:'TREND ZEE',price:1299,stock:22,colors:['Black'],sizes:['6','7','8','9','10'],images:['/images/sandal.jpg'],description:'Leave a little space in your schedule. Easy sandals for slower steps and sunnier days.',specifications:'Sample product • Adjustable buckle • Open toe • Wipe clean',tag:'SLOW IT DOWN'},
{id:'tz-006',name:'The easy slide',category:'Slippers',type:'Home',brand:'TREND ZEE',price:699,stock:25,colors:['Black'],sizes:['6','7','8','9','10'],images:['/images/slide.jpg'],description:'Your off-duty ritual starts here. Slip into something easy and make yourself at home.',specifications:'Sample product • Slip-on • Open toe • Wipe clean',tag:'AT EASE'}];
export const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
