export type Product={id:string;name:string;category:string;type:string;brand:string;price:number;mrp?:number;sku?:string;stock:number;colors:string[];sizes:string[];images:string[];hoverImage?:string;video?:string;badge?:string;tags?:string[];variantStock?:Record<string,number>;rating?:number;reviewCount?:number;description:string;specifications:string;material?:string;care?:string;shipping?:string;returnPolicy?:string;seoTitle?:string;seoDescription?:string;tag:string;};
export const categories=['All','Clothing','Bags','Shoes & Sandals','Slippers','Sunglasses'];
export const seedProducts:Product[]=[
{id:'tz-001',name:'The everyday crew',category:'Clothing',type:'Round neck T-shirts',brand:'TREND ZEE',price:799,mrp:999,sku:'TZ-TEE-001',stock:30,colors:['White','Black'],sizes:['S','M','L','XL'],images:['/images/tee.jpg','/images/shirt.jpg','/images/hero.jpg'],hoverImage:'/images/shirt.jpg',badge:'EVERYDAY EDIT',tags:['cotton','everyday','best seller'],rating:4.7,reviewCount:128,material:'Cotton jersey',care:'Machine wash cold · Wash dark colours separately',shipping:'Delivery availability and ETA are confirmed at checkout.',returnPolicy:'Eligible delivered paid orders can be returned within the store return window.',description:'A fresh start, every day. An easy crewneck for slow mornings, busy afternoons and everything in between.',specifications:'Sample product • Cotton jersey • Regular fit • Machine wash cold',tag:'THE DAILY ESSENTIAL'},
{id:'tz-002',name:'The city sneaker',category:'Shoes & Sandals',type:'Casual',brand:'TREND ZEE',price:2499,mrp:3199,sku:'TZ-SNK-002',stock:18,colors:['White / Sand'],sizes:['6','7','8','9','10','11'],images:['/images/sneaker.jpg','/images/sandal.jpg','/images/slide.jpg'],badge:'TRENDING',tags:['sneaker','casual','city'],rating:4.6,reviewCount:94,material:'Textile upper · Rubber outsole',care:'Wipe clean · Air dry',shipping:'Delivery availability and ETA are confirmed at checkout.',returnPolicy:'Eligible delivered paid orders can be returned within the store return window.',description:'Take the long way home. A versatile sneaker to carry your story from one street to the next.',specifications:'Sample product • Lace-up • Rubber outsole • Wipe clean',tag:'OFF THE CLOCK'},
{id:'tz-003',name:'The daytripper backpack',category:'Bags',type:'College bags',brand:'TREND ZEE',price:1899,mrp:2299,sku:'TZ-BAG-003',stock:15,colors:['Brown'],sizes:['One size'],images:['/images/bag.jpg','/images/hero.jpg','/images/shirt.jpg'],badge:'GO ANYWHERE',tags:['backpack','work','college'],rating:4.8,reviewCount:71,material:'Durable woven fabric',care:'Spot clean only',shipping:'Delivery availability and ETA are confirmed at checkout.',returnPolicy:'Eligible delivered paid orders can be returned within the store return window.',description:'Room for your plans. A compact carryall for your notebook, everyday essentials and a little spontaneity.',specifications:'Sample product • Adjustable straps • Zipped main compartment • Spot clean',tag:'GO SOMEWHERE'},
{id:'tz-004',name:'The after-hours shirt',category:'Clothing',type:'Mixed cotton',brand:'TREND ZEE',price:1499,mrp:1799,sku:'TZ-SHT-004',stock:20,colors:['Blue'],sizes:['S','M','L','XL'],images:['/images/shirt.jpg','/images/tee.jpg','/images/hero.jpg'],badge:'AFTER HOURS',tags:['shirt','evening','statement'],rating:4.5,reviewCount:58,material:'Cotton blend',care:'Machine wash cold · Steam or iron on low',shipping:'Delivery availability and ETA are confirmed at checkout.',returnPolicy:'Eligible delivered paid orders can be returned within the store return window.',description:'When the day changes pace, change the mood. A statement shirt for evenings worth remembering.',specifications:'Sample product • Collared shirt • Regular fit • Fabric to be confirmed',tag:'A LITTLE DIFFERENT'},
{id:'tz-005',name:'The weekend sandal',category:'Shoes & Sandals',type:'Home',brand:'TREND ZEE',price:1299,mrp:1599,sku:'TZ-SND-005',stock:22,colors:['Black'],sizes:['6','7','8','9','10'],images:['/images/sandal.jpg','/images/sneaker.jpg','/images/slide.jpg'],badge:'WEEKEND',tags:['sandal','summer','easy'],rating:4.7,reviewCount:43,material:'Comfort synthetic upper',care:'Wipe clean',shipping:'Delivery availability and ETA are confirmed at checkout.',returnPolicy:'Eligible delivered paid orders can be returned within the store return window.',description:'Leave a little space in your schedule. Easy sandals for slower steps and sunnier days.',specifications:'Sample product • Adjustable buckle • Open toe • Wipe clean',tag:'SLOW IT DOWN'},
{id:'tz-006',name:'The easy slide',category:'Slippers',type:'Home',brand:'TREND ZEE',price:699,mrp:899,sku:'TZ-SLD-006',stock:25,colors:['Black'],sizes:['6','7','8','9','10'],images:['/images/slide.jpg','/images/sandal.jpg','/images/sneaker.jpg'],badge:'AT EASE',tags:['slide','comfort','home'],rating:4.6,reviewCount:36,material:'Soft-touch EVA',care:'Wipe clean',shipping:'Delivery availability and ETA are confirmed at checkout.',returnPolicy:'Eligible delivered paid orders can be returned within the store return window.',description:'Your off-duty ritual starts here. Slip into something easy and make yourself at home.',specifications:'Sample product • Slip-on • Open toe • Wipe clean',tag:'AT EASE'}];
export const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
