import { integer, index, primaryKey, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const products=sqliteTable('products',{id:text('id').primaryKey(),data:text('data').notNull(),archived:integer('archived').notNull().default(0)});

export const records=sqliteTable('records',{id:text('id').primaryKey(),kind:text('kind').notNull(),owner:text('owner').notNull(),data:text('data').notNull(),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('records_kind_owner').on(t.kind,t.owner)]);

export const customers=sqliteTable('customers',{id:text('id').primaryKey(),email:text('email').notNull(),displayName:text('display_name'),mobile:text('mobile'),status:text('status').notNull().default('active'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('customers_email').on(t.email)]);

export const addresses=sqliteTable('addresses',{id:text('id').primaryKey(),customerId:text('customer_id').notNull(),label:text('label').notNull().default('Delivery'),name:text('name').notNull(),mobile:text('mobile').notNull(),addressLine1:text('address_line1').notNull(),addressLine2:text('address_line2'),city:text('city').notNull(),state:text('state'),pincode:text('pincode').notNull(),country:text('country').notNull().default('India'),isDefault:integer('is_default').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('addresses_customer').on(t.customerId)]);

export const productVariants=sqliteTable('product_variants',{id:text('id').primaryKey(),productId:text('product_id').notNull(),sku:text('sku'),barcode:text('barcode'),size:text('size'),color:text('color'),optionData:text('option_data').notNull().default('{}'),price:integer('price'),mrp:integer('mrp'),stock:integer('stock').notNull().default(0),lowStockThreshold:integer('low_stock_threshold').notNull().default(5),archived:integer('archived').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('product_variants_product').on(t.productId),index('product_variants_stock').on(t.stock)]);

export const categories=sqliteTable('categories',{id:text('id').primaryKey(),slug:text('slug').notNull(),name:text('name').notNull(),description:text('description'),image:text('image'),bannerImage:text('banner_image'),seoTitle:text('seo_title'),seoDescription:text('seo_description'),sortOrder:integer('sort_order').notNull().default(0),visible:integer('visible').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('categories_slug').on(t.slug)]);

export const collections=sqliteTable('collections',{id:text('id').primaryKey(),slug:text('slug').notNull(),title:text('title').notNull(),description:text('description'),coverImage:text('cover_image'),layout:text('layout').notNull().default('grid'),sortOrder:integer('sort_order').notNull().default(0),visible:integer('visible').notNull().default(1),startsAt:text('starts_at'),endsAt:text('ends_at'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('collections_slug').on(t.slug)]);

export const collectionProducts=sqliteTable('collection_products',{collectionId:text('collection_id').notNull(),productId:text('product_id').notNull(),sortOrder:integer('sort_order').notNull().default(0)},t=>[primaryKey({columns:[t.collectionId,t.productId]})]);

export const campaigns=sqliteTable('campaigns',{id:text('id').primaryKey(),name:text('name').notNull(),title:text('title').notNull(),description:text('description'),desktopImage:text('desktop_image'),mobileImage:text('mobile_image'),ctaLabel:text('cta_label'),ctaHref:text('cta_href'),category:text('category'),discountLabel:text('discount_label'),startDate:text('start_date'),endDate:text('end_date'),status:text('status').notNull().default('draft'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()});

export const homepageSections=sqliteTable('homepage_sections',{id:text('id').primaryKey(),type:text('type').notNull(),config:text('config').notNull().default('{}'),sortOrder:integer('sort_order').notNull().default(0),visible:integer('visible').notNull().default(1),startsAt:text('starts_at'),endsAt:text('ends_at'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('homepage_sections_order').on(t.sortOrder,t.visible)]);

export const inventoryMovements=sqliteTable('inventory_movements',{id:text('id').primaryKey(),productId:text('product_id').notNull(),variantId:text('variant_id'),beforeQty:integer('before_qty').notNull(),afterQty:integer('after_qty').notNull(),deltaQty:integer('delta_qty').notNull(),reason:text('reason').notNull(),actorId:text('actor_id'),createdAt:text('created_at').notNull()},t=>[index('inventory_movements_product').on(t.productId,t.createdAt)]);

export const orders=sqliteTable('orders',{id:text('id').primaryKey(),customerId:text('customer_id'),status:text('status').notNull(),paymentStatus:text('payment_status').notNull(),currency:text('currency').notNull().default('INR'),subtotal:integer('subtotal').notNull(),discount:integer('discount').notNull().default(0),shipping:integer('shipping').notNull().default(0),tax:integer('tax').notNull().default(0),total:integer('total').notNull(),couponCode:text('coupon_code'),shippingAddressId:text('shipping_address_id'),paymentIntentId:text('payment_intent_id'),courier:text('courier'),trackingNumber:text('tracking_number'),notes:text('notes'),placedAt:text('placed_at').notNull(),paidAt:text('paid_at'),deliveredAt:text('delivered_at'),cancelledAt:text('cancelled_at'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('orders_customer').on(t.customerId,t.createdAt),index('orders_status').on(t.status,t.paymentStatus)]);

export const orderItems=sqliteTable('order_items',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),productId:text('product_id').notNull(),variantId:text('variant_id'),productName:text('product_name').notNull(),sku:text('sku'),size:text('size'),color:text('color'),quantity:integer('quantity').notNull(),unitPrice:integer('unit_price').notNull(),mrp:integer('mrp'),lineTotal:integer('line_total').notNull()},t=>[index('order_items_order').on(t.orderId),index('order_items_product').on(t.productId)]);

export const payments=sqliteTable('payments',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),provider:text('provider').notNull(),providerPaymentId:text('provider_payment_id'),providerOrderId:text('provider_order_id'),amount:integer('amount').notNull(),currency:text('currency').notNull().default('INR'),status:text('status').notNull(),rawEvent:text('raw_event'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('payments_order').on(t.orderId),uniqueIndex('payments_provider_payment').on(t.provider,t.providerPaymentId)]);

export const coupons=sqliteTable('coupons',{code:text('code').primaryKey(),discountType:text('discount_type').notNull().default('percent'),percent:integer('percent'),fixedAmount:integer('fixed_amount'),minOrder:integer('min_order').notNull().default(0),maxDiscount:integer('max_discount'),productIds:text('product_ids').notNull().default('[]'),categories:text('categories').notNull().default('[]'),usageLimit:integer('usage_limit').notNull().default(0),perUserLimit:integer('per_user_limit').notNull().default(0),startsAt:text('starts_at'),endsAt:text('ends_at').notNull(),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()});

export const couponRedemptions=sqliteTable('coupon_redemptions',{id:text('id').primaryKey(),couponCode:text('coupon_code').notNull(),customerId:text('customer_id'),orderId:text('order_id'),amount:integer('amount').notNull(),createdAt:text('created_at').notNull()},t=>[index('coupon_redemptions_coupon').on(t.couponCode,t.createdAt),index('coupon_redemptions_customer').on(t.customerId,t.couponCode)]);

export const wishlists=sqliteTable('wishlists',{customerId:text('customer_id').notNull(),productId:text('product_id').notNull(),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.customerId,t.productId]})]);

export const recentlyViewed=sqliteTable('recently_viewed',{customerId:text('customer_id'),sessionId:text('session_id'),productId:text('product_id').notNull(),viewedAt:text('viewed_at').notNull()},t=>[index('recently_viewed_customer').on(t.customerId,t.viewedAt),index('recently_viewed_session').on(t.sessionId,t.viewedAt)]);

export const customerPreferences=sqliteTable('customer_preferences',{customerId:text('customer_id').primaryKey(),data:text('data').notNull().default('{}'),updatedAt:text('updated_at').notNull()});

export const reviews=sqliteTable('reviews',{id:text('id').primaryKey(),productId:text('product_id').notNull(),customerId:text('customer_id'),orderId:text('order_id'),rating:integer('rating').notNull(),title:text('title'),body:text('body').notNull(),imageUrls:text('image_urls').notNull().default('[]'),helpfulCount:integer('helpful_count').notNull().default(0),status:text('status').notNull().default('pending'),moderationNote:text('moderation_note'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('reviews_product_status').on(t.productId,t.status,t.createdAt)]);

export const supportTickets=sqliteTable('support_tickets',{id:text('id').primaryKey(),customerId:text('customer_id'),orderId:text('order_id'),category:text('category').notNull(),subject:text('subject').notNull(),message:text('message').notNull(),status:text('status').notNull().default('New'),internalNote:text('internal_note'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('support_tickets_status').on(t.status,t.updatedAt)]);

export const returns=sqliteTable('returns',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),customerId:text('customer_id'),reason:text('reason').notNull(),status:text('status').notNull().default('Requested'),refundAmount:integer('refund_amount').notNull().default(0),internalNote:text('internal_note'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('returns_order').on(t.orderId),index('returns_status').on(t.status,t.updatedAt)]);

export const adminUsers=sqliteTable('admin_users',{id:text('id').primaryKey(),email:text('email').notNull(),displayName:text('display_name').notNull(),role:text('role').notNull().default('Owner'),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('admin_users_email').on(t.email)]);
