'use client';

import { useEffect, useMemo, useState } from 'react';
import { Filter, Heart, Search, SlidersHorizontal, Star, ArrowRight } from 'lucide-react';
import { Toaster, toast } from 'sonner';
import type { Product } from '@/lib/catalog';
import { money } from '@/lib/catalog';
import { api } from '@/lib/client';

export default function ShopPage(){
  const [products,setProducts]=useState<Product[]>([]);
  const [saved,setSaved]=useState<string[]>([]);
  const [query,setQuery]=useState('');
  const [category,setCategory]=useState('All');
  const [brand,setBrand]=useState('All brands');
  const [size,setSize]=useState('All sizes');
  const [color,setColor]=useState('All colours');
  const [min,setMin]=useState(''); const [max,setMax]=useState('');
  const [rating,setRating]=useState('All'); const [onlyDiscounted,setOnlyDiscounted]=useState(false);
  const [sort,setSort]=useState('Relevance'); const [showFilters,setShowFilters]=useState(false); const [loading,setLoading]=useState(true); const [recentSearches,setRecentSearches]=useState<string[]>([]);
  useEffect(()=>{(async()=>{try{const r=await fetch('/api/store');const d:any=await r.json();if(!r.ok)throw new Error(d.error);setProducts(d.products||[]);setSaved(d.cart?.saved||[]);const p=new URLSearchParams(location.search);setCategory(p.get('category')||'All');setQuery(p.get('q')||'');try{setRecentSearches(JSON.parse(localStorage.getItem('tz_recent_searches')||'[]').slice(0,6))}catch{}}catch(e){toast.error((e as Error).message)}finally{setLoading(false)}})()},[]);
  const cats=['All',...Array.from(new Set(products.map(p=>p.category))).filter(Boolean).sort()];
  const brands=['All brands',...Array.from(new Set(products.map(p=>p.brand))).filter(Boolean).sort()];
  const sizes=['All sizes',...Array.from(new Set(products.flatMap(p=>p.sizes))).filter(Boolean).sort()];
  const colors=['All colours',...Array.from(new Set(products.flatMap(p=>p.colors))).filter(Boolean).sort()];
  const filtered=useMemo(()=>{let r=products.filter(p=>{const q=query.trim().toLowerCase();if(category!=='All'&&p.category!==category)return false;if(brand!=='All brands'&&p.brand!==brand)return false;if(size!=='All sizes'&&!p.sizes.includes(size))return false;if(color!=='All colours'&&!p.colors.includes(color))return false;if(min&&p.price<Number(min))return false;if(max&&p.price>Number(max))return false;if(rating!=='All'&&(p.rating||0)<Number(rating))return false;if(onlyDiscounted&&!(p.mrp&&p.mrp>p.price))return false;if(q&&!matchesProductQuery(p,query))return false;return true});if(sort==='Price low to high')r.sort((a,b)=>a.price-b.price);if(sort==='Price high to low')r.sort((a,b)=>b.price-a.price);if(sort==='Rating')r.sort((a,b)=>(b.rating||0)-(a.rating||0));if(sort==='Discount')r.sort((a,b)=>((b.mrp||b.price)-b.price)/Math.max(1,b.mrp||b.price)-((a.mrp||a.price)-a.price)/Math.max(1,a.mrp||a.price));return r},[products,query,category,brand,size,color,min,max,rating,onlyDiscounted,sort]);
  async function wishlist(id:string){try{const r=await fetch('/api/store');const d:any=await r.json();const list=d.cart?.saved||[];const next=list.includes(id)?list.filter((x:string)=>x!==id):list.concat(id);await api('cart',{items:d.cart?.items||[],saved:next});setSaved(next);toast.success(next.includes(id)?'Saved to wishlist':'Removed from wishlist')}catch(e){toast.error((e as Error).message)}}
  const submitSearch=()=>{const term=query.trim();if(term){const next=[term,...recentSearches.filter(x=>x.toLowerCase()!==term.toLowerCase())].slice(0,6);setRecentSearches(next);try{localStorage.setItem('tz_recent_searches',JSON.stringify(next))}catch{}}}; const clear=()=>{setCategory('All');setBrand('All brands');setSize('All sizes');setColor('All colours');setMin('');setMax('');setRating('All');setOnlyDiscounted(false);setQuery('');setSort('Relevance')};
  if(loading)return <div className='store-loading'><span className='logo'>TREND ZEE</span><p>Loading the collection…</p></div>;
  return <><Toaster richColors/><header className='store-header shop-header'><a className='logo' href='/'>TREND ZEE<sup>®</sup></a><nav className='desktop-nav'><a href='/shop'>Shop</a><a href='/?section=trending'>Trending</a><a href='/?section=new'>New arrivals</a><a href='/?section=categories'>Categories</a></nav><div className='header-actions'><a href='/search' aria-label='Search'><Search size={19}/></a><a href='/wishlist' aria-label='Wishlist'><Heart size={19}/></a><a href='/' aria-label='Bag'>Bag</a></div></header>
  <main className='shop-page-shell'><div className='shop-hero'><span className='eyebrow'>THE TREND-ZEE EDIT</span><h1>Find what fits your next chapter.</h1><p>Search by style, filter with intent, and keep your favourites close.</p><form className='shop-search' onSubmit={e=>{e.preventDefault();submitSearch();}}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search shirts, sneakers, bags…'/><button type='button' onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal size={16}/> Filters</button></form>{recentSearches.length>0&&<div className='recent-searches'><span>Recent</span>{recentSearches.map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div>}</div>
  <div className='shop-toolbar'><span>{filtered.length} pieces</span><select value={sort} onChange={e=>setSort(e.target.value)}><option>Relevance</option><option>Price low to high</option><option>Price high to low</option><option>Rating</option><option>Discount</option></select></div>
  <div className={showFilters?'shop-layout filters-on':'shop-layout'}><aside className='shop-filters'><div className='filter-head'><b>Refine</b><button onClick={clear}>Reset</button></div><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label>Brand<select value={brand} onChange={e=>setBrand(e.target.value)}>{brands.map(x=><option key={x}>{x}</option>)}</select></label><label>Size<select value={size} onChange={e=>setSize(e.target.value)}>{sizes.map(x=><option key={x}>{x}</option>)}</select></label><label>Colour<select value={color} onChange={e=>setColor(e.target.value)}>{colors.map(x=><option key={x}>{x}</option>)}</select></label><div className='shop-range'><label>Min ₹<input value={min} onChange={e=>setMin(e.target.value.replace(/\D/g,''))}/></label><label>Max ₹<input value={max} onChange={e=>setMax(e.target.value.replace(/\D/g,''))}/></label></div><label>Rating<select value={rating} onChange={e=>setRating(e.target.value)}><option>All</option><option value='4'>4★ & up</option><option value='3'>3★ & up</option></select></label><label className='check-line'><input type='checkbox' checked={onlyDiscounted} onChange={e=>setOnlyDiscounted(e.target.checked)}/><span>On sale only</span></label></aside><section><div className='shop-grid'>{filtered.map(p=><article className='shop-card' key={p.id}><a href={'/product/'+p.id} className='shop-card-img'><img src={p.images[0]} alt={p.name} loading='lazy'/>{p.badge&&<span>{p.badge}</span>}<button type='button' aria-label={'Wishlist '+p.name} onClick={e=>{e.preventDefault();e.stopPropagation();wishlist(p.id)}}><Heart size={17} fill={saved.includes(p.id)?'currentColor':'none'}/></button></a><div className='shop-card-body'><div className='split'><a href={'/product/'+p.id}><h2>{p.name}</h2></a><b>{money(p.price)}</b></div><p>{p.brand} · {p.type}</p><div className='shop-card-meta'>{p.rating&&<span><Star size={12} fill='currentColor'/> {p.rating.toFixed(1)} <small>({p.reviewCount||0})</small></span>}{p.mrp&&p.mrp>p.price&&<span>{Math.round((1-p.price/p.mrp)*100)}% off</span>}</div></div></article>)}</div>{!filtered.length&&<div className='empty'><Filter size={32}/><h2>No pieces match.</h2><p>Try another filter or reset the edit.</p><button className='button' onClick={clear}>Show everything</button></div>}</section></div>
  <section className='shop-discovery'><span className='eyebrow'>KEEP EXPLORING</span><h2>See the story behind the products.</h2><a className='button' href='/'>Return to the Trend-Zee experience <ArrowRight size={16}/></a></section></main></>;
}