'use client';

import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Check,ChevronRight,Heart,Minus,Plus,RotateCcw,Share2,ShieldCheck,ShoppingBag,Star,Truck} from 'lucide-react';
import {toast} from 'sonner';
import {Toaster} from 'sonner';
import {money,Product} from '@/lib/catalog';
import {api} from '@/lib/client';

export default function ProductPage({params}:{params:{id:string}}){
 const [product,setProduct]=useState<Product|null>(null);const [products,setProducts]=useState<Product[]>([]);const [reviews,setReviews]=useState<any[]>([]);const [saved,setSaved]=useState(false);const [size,setSize]=useState('');const [color,setColor]=useState('');const [photo,setPhoto]=useState(0);const [qty,setQty]=useState(1);const [pincode,setPincode]=useState('');const [delivery,setDelivery]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/store');const d:any=await r.json();if(!r.ok)throw new Error(d.error);const p=(d.products||[]).find((x:Product)=>x.id===params.id);if(!p)throw new Error('Product not found.');setProduct(p);setProducts(d.products||[]);setReviews((d.reviews||[]).filter((x:any)=>x.productId===params.id));setSize(p.sizes[0]||'');setColor(p.colors[0]||'');setSaved(!!d.cart?.saved?.includes(params.id));try{const ids=[params.id,...JSON.parse(localStorage.getItem('tz_recent')||'[]').filter((x:string)=>x!==params.id)].slice(0,8);localStorage.setItem('tz_recent',JSON.stringify(ids));}catch{}}catch(e){setError((e as Error).message)}})()},[params.id]);
 const average=reviews.length?reviews.reduce((s:number,r:any)=>s+Number(r.rating||0),0)/reviews.length:product?.rating||0;
 const related=useMemo(()=>product?[...products].filter(p=>p.id!==product.id&&((p.category===product.category)||p.tags?.some(t=>product.tags?.includes(t)))).slice(0,4):[],[products,product]);
 async function add(){if(!product||product.stock<=0)return;setBusy(true);try{const r=await fetch('/api/store');const d:any=await r.json();const items=[...(d.cart?.items||[])];const idx=items.findIndex((i:any)=>i.productId===product.id&&i.size===size&&i.color===color);if(idx<0)items.push({productId:product.id,quantity:qty,size,color});else items[idx]={...items[idx],quantity:Math.min(10,items[idx].quantity+qty)};await api('cart',{items,saved:d.cart?.saved||[]});toast.success('Added to bag');}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function toggleSave(){try{const r=await fetch('/api/store');const d:any=await r.json();const list=d.cart?.saved||[];const next=list.includes(params.id)?list.filter((x:string)=>x!==params.id):[...list,params.id];await api('cart',{items:d.cart?.items||[],saved:next});setSaved(next.includes(params.id));toast.success(next.includes(params.id)?'Saved for later':'Removed from saved');}catch(e){toast.error((e as Error).message)}}
 if(error)return <main className="product-page-shell"><Toaster richColors/><a className="text-button" href="/"><ArrowLeft size={16}/> Back to Trend-Zee</a><div className="empty"><h1>We could not find that product.</h1><p>{error}</p><a className="button" href="/shop">Shop the collection</a></div></main>;
 if(!product)return <main className="store-loading"><span className="logo">TREND ZEE</span><p>Loading product…</p></main>;
 return <><Toaster richColors position="top-center"/><main className="product-page-shell">
  <div className="product-page-top"><a className="text-button" href="/shop"><ArrowLeft size={16}/> Back to shop</a><button className="text-button" onClick={async()=>{try{await navigator.share?.({title:product.name,text:product.description,url:location.href});}catch{await navigator.clipboard.writeText(location.href);toast.success('Link copied')}}}><Share2 size={16}/> Share</button></div>
  <div className="pdp-grid"><div><div className="pdp-main-image"><img src={product.images[photo]||product.images[0]} alt={product.name}/>{product.badge&&<span className="product-tag">{product.badge}</span>}</div><div className="pdp-thumbs">{product.images.map((src,i)=><button className={i===photo?'active':''} key={src+i} onClick={()=>setPhoto(i)}><img src={src} alt={product.name+' view '+(i+1)}/></button>)}</div>{product.video&&<video className="pdp-video" controls preload="metadata" poster={product.images[0]} src={product.video}/>}</div>
   <div className="pdp-copy"><span className="eyebrow">{product.tag||product.category}</span><h1>{product.name}</h1><div className="pdp-rating"><Star size={16} fill="currentColor"/><b>{average?average.toFixed(1):'—'}</b><span>{reviews.length||product.reviewCount||0} reviews</span></div><div className="pdp-price"><b>{money(product.price)}</b>{product.mrp&&product.mrp>product.price&&<><s>{money(product.mrp)}</s><span>{Math.round((1-product.price/product.mrp)*100)}% off</span></>}</div><p>{product.description}</p>
    <div className="pdp-option-grid"><label>Size<select value={size} onChange={e=>setSize(e.target.value)}>{product.sizes.map(x=><option key={x}>{x}</option>)}</select></label><label>Colour<select value={color} onChange={e=>setColor(e.target.value)}>{product.colors.map(x=><option key={x}>{x}</option>)}</select></label></div>
    <div className="pdp-quantity"><span>Quantity</span><div><button onClick={()=>setQty(Math.max(1,qty-1))} aria-label="Decrease quantity"><Minus size={15}/></button><b>{qty}</b><button onClick={()=>setQty(Math.min(10,Math.min(product.stock,qty+1)))} aria-label="Increase quantity"><Plus size={15}/></button></div></div>
    <div className="pdp-actions"><button className="button full" disabled={busy||product.stock<=0} onClick={add}>{product.stock<=0?'Out of stock':'Add to bag'} <ShoppingBag size={16}/></button><button className={saved?'save-wide saved':'save-wide'} onClick={toggleSave}><Heart size={17} fill={saved?'currentColor':'none'}/>{saved?'Saved':'Wishlist'}</button></div>
    <div className="pdp-facts"><div><ShieldCheck/><span><b>Secure shopping</b><small>Payment details only go through the configured payment provider.</small></span></div><div><Truck/><span><b>Delivery check</b><small>Enter a six-digit PIN to see the current fulfilment status.</small></span></div><div><RotateCcw/><span><b>Returns</b><small>{product.returnPolicy||'Eligible delivered paid orders can be returned within the configured window.'}</small></span></div></div>
    <div className="pdp-delivery"><label>Check delivery PIN<input inputMode="numeric" maxLength={6} value={pincode} onChange={e=>{setPincode(e.target.value.replace(/\D/g,''));setDelivery('')}} placeholder="e.g. 560001"/></label><button className="button outline compact" disabled={!/^\d{6}$/.test(pincode)} onClick={()=>setDelivery('Delivery serviceability is checked after a shipping provider is connected. Your PIN '+pincode+' is formatted correctly.')}>Check</button>{delivery&&<p className="notice"><Check size={15}/> {delivery}</p>}</div>
    <details open><summary>Product details</summary><p><b>Material:</b> {product.material||'See specifications'}<br/><b>Care:</b> {product.care||product.specifications}</p></details><details><summary>Shipping & returns</summary><p>{product.shipping||'Delivery availability and ETA are confirmed before paid checkout.'}<br/>{product.returnPolicy||'Eligible delivered paid orders can request a return within the configured return window.'}</p></details>
    {reviews.length>0&&<section className="pdp-reviews"><h2>Customer reviews</h2>{reviews.slice(0,6).map((r:any)=><article key={r.id||r.created}><div className="split"><b>{r.title||'Customer review'}</b><span>{'★'.repeat(Number(r.rating||0))}</span></div><p>{r.message}</p><small>{r.name||'Customer'} · {new Date(r.created).toLocaleDateString('en-IN')}</small></article>)}</section>}
   </div></div>
  {related.length>0&&<section className="pdp-related"><div className="section-heading"><div><span className="eyebrow">COMPLETE THE EDIT</span><h2>More from this story.</h2></div></div><div className="pdp-related-grid">{related.map(p=><a key={p.id} href={'/product/'+p.id} className="related-card"><img src={p.images[0]} alt={p.name}/><span><b>{p.name}</b><small>{money(p.price)}</small></span><ChevronRight size={16}/></a>)}</div></section>}
 </main><div className="mobile-purchase-bar"><span><b>{money(product.price)}</b><small>{product.stock>0?'In stock':'Out of stock'}</small></span><button className="button" disabled={busy||product.stock<=0} onClick={add}>Add to bag</button></div></>;
}
